[[_chapter_installing_the_media_server]]
= Installing the Media Server

The {this-platform} {this-application} is available in both binary and source code distributions.

The simplest way to get started with the Media Server is to download the ready-to-run binary distribution from the https://github.com/RestComm/mediaserver/releases/latest[releases page].
Alternatively, the source code for the Media Server can be obtained by checking it out https://github.com/RestComm/mediaserver[from its repository] using the Git version control system. You can later run a build using Maven.

The binary distribution is recommended for most users.
Downloading and building the source code is recommended for those who want access to the latest revisions and Media Server capabilities.

Installing the <<_jdk_installing_configuring_and_running>>

[[_itms-binary-standalone_media_server-installing_configuring_and_running]]
== Standalone Media Server Binary Distribution

[[_itms_binary_standalone_media_server_preinstall_requirements_and_prerequisites]]
=== Pre-Install Requirements and Prerequisites

Ensure that the following requirements have been met before continuing with the installation:

.Hardware Requirements
Sufficient Disk Space::
Once unzipped, the {this-platform} {this-application} binary release requires _at least_	36Mb of free disk space. Keep in mind that disk space requirements may change in future iterations.


.Software Requirements
Java Development Kit::
A working installation of JDK 8 is required for {this-platform} {this-application} to run.

[[_itms_binary_standalone_media_server_downloading]]
=== Downloading

The latest version of the {this-platform} {this-application} is available from the project's https://github.com/RestComm/media-server-standalone/releases/latest[github release page].
Select the link named _restcomm-media-server-<version>.zip_ to start downloading the latest stable binary release from community.

[[_itms_binary_standalone_media_server_installing]]
=== Installing

Once the requirements and prerequisites have been met, the {this-platform} {this-application} can be installed into the system.
Follow the instructions below for the operating system on which the server will reside. 

.Procedure: Installing the {this-platform} {this-application} Binary Distribution on Linux

It is assumed that the downloaded archive is saved in the home directory, and that a terminal window is open displaying the home directory. 

. Create a subdirectory into which the files can be extracted. For ease of identification, it is recommended that the version number of the binary is included in this directory name.
+
----
~]$ mkdir restcomm-media-server-<version>
----

. Move the downloaded zip file into the directory:
+
----
~]$ mv restcomm-media-server-<version>.zip restcomm-media-server-<version>
----

. Move into the directory:
+
----
~]$ cd	restcomm-media-server-<version>
----

. Extract the files into the current directory:
+
----
restcomm-media-server-<version>]$ unzip restcomm-media-server-<version>.zip
----

. Consider deleting the archive, if free disk space is an issue. 
+
----
restcomm-media-server-<version>]$ rm restcomm-media-server-<version>.zip
----

[[_itms_binary_standalone_media_server_running]]
=== Running

Now that the {this-platform} {this-application} binary has been downloaded and properly installed in a local directory, we can bootstrap the project by following these steps:

. Change the working directory to installation directory (the one into which the zip file's contents was extracted) 
+
----
~]$ cd restcomm-media-server-<version>
----

. (Optional) Ensure that the [path]_bin/run.sh_ start script is executable. 
+
----
restcomm-media-server-<version>]$ chmod +x bin/run.sh
----

. Execute the [path]_run.sh_ shell script. 
+
----
restcomm-media-server-<version>]$ ./bin/run.sh
----

You can verify that {this-platform} {this-application} has started successfully if the last line of output in the Linux Terminal window is similar to 

[source]
----
  _____           _    _____
 |  __ \         | |  / ____|
 | |__) |___  ___| |_| |     ___  _ __ ___  _ __ ___
 |  _  // _ \/ __| __| |    / _ \| '_ ` _ \| '_ ` _ \
 | | \ \  __/\__ \ |_| |___| (_) | | | | | | | | | | |
 |_|  \_\___||___/\__|\_____\___/|_| |_| |_|_| |_| |_|
 |  \/  |        | (_)        / ____|
 | \  / | ___  __| |_  __ _  | (___   ___ _ ____   _____ _ __
 | |\/| |/ _ \/ _` | |/ _` |  \___ \ / _ \ '__\ \ / / _ \ '__|
 | |  | |  __/ (_| | | (_| |  ____) |  __/ |   \ V /  __/ |
 |_|  |_|\___|\__,_|_|\__,_| |_____/ \___|_|    \_/ \___|_|

 :: Version 8.0.0-SNAPSHOT ::


09:36:43,666 INFO  [SpringApplication] (main) Starting application with PID 55792
09:36:43,668 INFO  [SpringApplication] (main) No active profile set, falling back to default profiles: default
09:36:43,709 INFO  [AnnotationConfigApplicationContext] (main) Refreshing org.springframework.context.annotation.AnnotationConfigApplicationContext@4716be8b: startup date [Thu Mar 15 09:36:43 WET 2018]; root of context hierarchy
09:36:44,580 INFO  [MgcpEndpointManager] (main) Installed MGCP Endpoint Provider for namespace restcomm/bridge/
09:36:44,580 INFO  [MgcpEndpointManager] (main) Installed MGCP Endpoint Provider for namespace restcomm/ivr/
09:36:44,580 INFO  [MgcpEndpointManager] (main) Installed MGCP Endpoint Provider for namespace restcomm/cnf/
09:36:44,601 INFO  [PriorityQueueScheduler] (main) Starting
09:36:44,603 INFO  [PriorityQueueScheduler] (main) Started
09:36:44,604 INFO  [ServiceScheduler] (main) Started scheduler!
09:36:44,604 INFO  [UdpManager] (main) Starting UDP Manager
09:36:44,605 INFO  [UdpManager] (main) Initialized UDP interface[unknown]: bind address=127.0.0.1
09:36:44,683 INFO  [StandaloneMediaServer] (main) Media Server started
----

[[_itms-binary-standalone_media_server-stopping]]
=== Stopping

To stop the execution of an active {this-platform} {this-application} process, we a couple of possibilities:

. Send interrupt signal (Ctrl+C) to the active Linux Terminal session where {this-platform} {this-application} process is running.

. Find the PID of the {this-platform} {this-application} Java process and kill it:
+
----
~]$ ps aux | grep java
hrosa            10947  16.8 22.4  6603132 3755516 s005  S+    3:51PM   0:07.51 /opt/.jenv/versions/1.8/bin/java -Dprogram.name=run.sh -classpath /opt/restcomm-media-server/bin/run.jar org.mobicents.media.server.bootstrap.Main
~]$ kill 10947
----

[[_itms_binary_standalone_media_server_running_session]]
== Running with Session Management

The RestComm Media Server allows users to bootstrap the project using https://tmux.github.io[TMux], a terminal multiplexer that lets users switch easily between several programs in one terminal, detach them (they keep running in the background) and reattach them to a different terminal.

.Tmux installation
----
# CentOS/RHEL
yum install tmux

# Ubuntu/Debian
apt-get install tmux

# macOS
homebrew install tmux
----

=== Starting
The run the project via Tmux, users simply need to execute the `MS_HOME/bin/start-media-server.sh` script.

[source,shell]
----
bash-3.2# ./start-mediaserver.sh
Starting RestComm Media Server...
...RestComm Media Server started running on session named "mediaserver"!
----

From the Terminal output, we see the script created a tmux session named `mediaserver` where the Media Server process will be running.

[source,shell]
----
bash-3.2# tmux ls
mediaserver: 1 windows (created Wed Nov  2 22:05:14 2016) [160x35]
----

To access the _mediaserver_ session we just need to run the following command:

[source,shell]
----
bash-3.2# tmux attach -t mediaserver
----

To detach from tmux session, just press `ctrl+b d` from within tmux console.

[[_ctms_configuring_the_media_server_automatic_stopping]]
=== Stopping

To stop the Media Server process and kill the tmux session, the user simply needs to execute the stop-mediaserver.sh script.

[source,shell]
----
bash-3.2# ./stop-mediaserver.sh
Stopping RestComm Media Server...
...stopped RestComm Media Server instance running on session "mediaserver".

bash-3.2# tmux ls
no server running on /private/tmp/tmux-501/default
----


[[_itms_standalone_server_structure]]
=== Server Structure

Now that the server is installed, it is important to understand the layout of the server directories.
An understanding of the server structure is useful when deploying examples, and making configuration changes.
It is also useful to understand what components can be removed to reduce the server boot time. 

The directory structure in the {this-platform} {this-application} installation directory is named using a standard structure. <<_tab_mms_jboss_directory_structure>> describes each directory as well as the type of information contained within each location.

[[_tab_mms_jboss_directory_structure]]
.Directory Structure
[cols="1,1", frame="all", options="header"]
|===
| Directory Name | Description
| bin | Contains the entry point JARs and start-up scripts included with the Media Server distribution.
| conf | Contains the core services that are required for the server. This includes the bootstrap descriptor, log files, and the default media server configuration file.
| lib | Contains the dependency files required by the server.
| log | Contains the logs from the bootstrap logging service. The log directory is the default directory into which the bootstrap logging service places its logs, however, the location can be overridden by altering the log4j.xml configuration file. This file is located in the _conf_ directory.					
|===

The standalone Media Server uses a number of YAML configuration
files that control various aspects of the server.
<xref linkend="tab-mms-standalone_core_configuration_file_set" />
describes the location of the key configuration files,
and provides a description of the


[[_tab_mms_standalone_core_configuration_file_set]]
.Core Configuration File Set
[cols="1,1", frame="all", options="header"]
|===
| File Name and Location | Description
| conf/media-server.yml | Main configuration file responsible for configure all aspects of the Media Server core. For in-depth details of this file please see chapter 3.
| conf/media-plugin-*.yml | Configuration file for plugins. Each plugin will feature its own configuration file.
| conf/media-extra.yml | Utility file to override required configuration parameters without changing default values established in media-server.yml or plugin configuration files.
| conf/log4j2.yml| Specifies the Apache Log4j2 framework category priorities and appenders used by the Media Server.
|===

[[_itms_writing_and_running_tests_against_the_media_server]]
=== Writing and Running Tests Against the Media Server

For information about the different kinds of tests that the Media Server provides, refer to http://groups.google.com/group/mobicents-public/web/mobicents-ms-tests[Writing and Running Tests Against RestComm MS]			 


