# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.vm.box = "bento/ubuntu-16.04"

  vm_static_ip_address = "192.168.33.10" # this IP address is kind of important, and a big deal. Not the particular value, per se, but the fact that RC + RMS **MUST** know
  # what IP address they are running on. If you change this, please also ensure you change the values in `media-server.yml`, as well as the RC configuration (env vars, etc.).

  config.vm.network "forwarded_port", guest: 8080, host: 8080, guest_ip: vm_static_ip_address
  config.vm.network "forwarded_port", guest: 8443, host: 8443, guest_ip: vm_static_ip_address
  config.vm.network "forwarded_port", guest: 5080, host: 5080, guest_ip: vm_static_ip_address
  config.vm.network "forwarded_port", guest: 5080, host: 5080, guest_ip: vm_static_ip_address, protocol: "udp"
  config.vm.network "forwarded_port", guest: 5081, host: 5081, guest_ip: vm_static_ip_address
  config.vm.network "forwarded_port", guest: 5082, host: 5082, guest_ip: vm_static_ip_address
  config.vm.network "forwarded_port", guest: 5083, host: 5083, guest_ip: vm_static_ip_address
  for i in 65000..65050
      config.vm.network :forwarded_port, guest: i, host: i, guest_ip: vm_static_ip_address
  end

  # Create a private network, which allows host-only access to the machine
  # using a specific IP.
  config.vm.network "private_network", ip: vm_static_ip_address

  # Create a public network, which generally matched to bridged network.
  # Bridged networks make the machine appear as another physical device on
  # your network.
  # config.vm.network "public_network"

  config.vm.provider "virtualbox" do |vb|
    vb.memory = "8192"
    vb.cpus = 4 # you need at least 2. Or else.
  end

  config.vm.provision "shell", inline: <<-SHELL
    # 0. Update apt package index
    apt-get update

    ## Install Docker, as per official guide for ubuntu 16.04

    # 1. remove existing docker versions
    sudo apt-get remove docker docker-engine docker.io
    
    # 2. Install packages to allow apt to use a repository over HTTPS
    apt-get install -y \
        apt-transport-https \
        ca-certificates \
        curl \
        software-properties-common

    # 3. Add Docker’s official GPG key:
    curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -

    # 4. Add docker stable repository.
    sudo add-apt-repository \
       "deb [arch=amd64] https://download.docker.com/linux/ubuntu \
       $(lsb_release -cs) \
       stable"

    # 5. Update the apt package index now that new repo has been added.
    apt-get update
    
    # 6. Install docker ce
    apt-get install -y docker-ce

    # 7. Install Docker Compose
    curl -L https://github.com/docker/compose/releases/download/1.21.0/docker-compose-$(uname -s)-$(uname -m) -o /usr/local/bin/docker-compose && chmod +x /usr/local/bin/docker-compose

    # 8. Start Docker daemon
    service docker start

    # 9. Start 
    cd /vagrant 
    docker-compose up -d

  SHELL
end


