mediaserver:

  network:
    address: 192.168.33.10
    network: 192.168.33.0
    subnet: 255.255.255.0

  controller:
    mgcp:
      address: 192.168.33.10
      endpoints:
        - name: "mobicents/bridge/"
          relay: splitter
        - name: "mobicents/ivr/"
          relay: mixer
        - name: "mobicents/cnf/"
          relay: mixer

  media:
    lowPort: 65000
    highPort: 65050
    codecs:
      - pcmu
      - pcma
      - telephone-event

  dtls:
    certificate:
      path: "/opt/mediaserver/conf/dtls/x509-server-ecdsa.pem"
      key: "/opt/mediaserver/conf/dtls/x509-server-key-ecdsa.pem"
